/**
 * Created by Stone on 24/11/2016.
 */

//categories.
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const SELECT_CATEGORY = "SELECT_CATEGORY";

//subcategories.
export const SUBCATEGORIES_REQUEST = 'SUBCATEGORIES_REQUEST';
export const SUBCATEGORIES_SUCCESS = 'SUBCATEGORIES_SUCCESS';
export const SUBCATEGORIES_FAILURE = 'SUBCATEGORIES_FAILURE';
export const SELECT_SUBCATEGORY = 'SELECT_SUBCATEGORY';

//problem report page

///price tags:
export const PRICETAGS_REQUEST = 'PRICETAGS_REQUEST';
export const PRICETAGS_SUCCESS = 'PRICETAGS_SUCCESS';
export const PRICETAGS_FAILURE = 'PRICETAGS_FAILURE';

///submit problem:
export const SUBMIT_PROBLEM_REQUEST = 'SUBMIT_PROBLEM_REQUEST';
export const SUBMIT_PROBLEM_SUCCESS = 'SUBMIT_PROBLEM_SUCCESS';
export const SUBMIT_PROBLEM_FAILURE = 'SUBMIT_PROBLEM_FAILURE';


//address management page:
//get address list    get
export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAILURE = 'ADDRESS_LIST_FAILURE';

//delete one address  delete
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';

//edit one address  put
export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';

//edit one address  add
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';





export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESSS';




